### ISSUE TITLE
Upgrade to d3 v6

### ISSUE THREAD

**Issue by Blaapje** [fvanwijk/d3-area-chunked#1]
As d3 v5 is no longer maintained and upgrading to v6 introduces breaking changes, it would be nice if this package could upgrade to v6 as well.

**Comment by fvanwijk** [comment]
@mikewoudenberg Please also review PR #2.

If everything works fine, you could also create a similar PR for pbeshai/d3-line-chunked, however I doubt if it will be merged because the project looks [abandoned](https://github.com/pbeshai/d3-line-chunked/issues/16).
